### ISSUE TITLE
请问项目还继续维护吗？

### ISSUE THREAD

**Issue by mrxiaozhuox** [oovm/dioxus-hooks#1]
Dioxus 0.3X 已经发布了，想问一下作者还会继续维护吗，因为我这边有几个项目引用了这个包，如果不打算维护了我这边Fork一份重新来。

**Comment by oovm** [comment]
简单更新了一下 api

**Comment by oovm** [comment]
我最近不写前端了, 你需要的话我把 repo 和 crates 转给你

**Comment by mrxiaozhuox** [comment]
没事的，后续如果要更新的话，我可以做Fork
